@startgantt
!define kbvcolor #e65100
!define evdgacolor #df8a5d
!define davcolor #2e7d32
!define gematikcolor #2E5077
!define gematikcolor_fdv #213555
!define gematikcolor_patrn #4DA1A9
!define gematikcolor_eu #93a8bc
!define datelinecolor #EFD0CA
!define erpfdcolor #607D8B

<style>
ganttDiagram {
   task {
      BackGroundColor GreenYellow
      LineColor Green
      FontColor black
      FontSize 18
      FontStyle bold
   }
}
</style>

title Zeitleiste der Versionsübergänge der FHIR-Profile
footer Zuletzt verändert am %date("dd.MM.yyyy")

projectscale monthly zoom 3
Project starts 2025-07-05

-- ERP-FD Konfigurationen --

2025-07-15 is colored datelinecolor
2025-09-30 is colored datelinecolor

[Start Gültigkeit erp_2025_04 (15.07.2025)] happens on 2025-07-15
[Ende Gültigkeit erp_2025_04 (30.09.2025)] happens on 2025-09-30

[erp_2025_04] starts 2025-07-15
[erp_2025_04] ends 2025-09-30
[erp_2025_04] is colored in erpfdcolor

2025-10-01 is colored datelinecolor
2026-01-11 is colored datelinecolor

[Start Gültigkeit erp_2025_05 (01.10.2025)] happens on 2025-10-01
[Ende Gültigkeit erp_2025_05 (11.01.2026)] happens on 2026-01-11

[erp_2025_05] starts 2025-10-01
[erp_2025_05] ends 2026-01-11
[erp_2025_05] is colored in erpfdcolor

2026-01-12 is colored datelinecolor
2026-03-31 is colored datelinecolor

[Start Gültigkeit erp_2026_01 (12.01.2026)] happens on 2026-01-12
[Ende Gültigkeit erp_2026_01 (31.03.2026)] happens on 2026-03-31

[erp_2026_01] starts 2026-01-12
[erp_2026_01] ends 2026-03-31
[erp_2026_01] is colored in erpfdcolor

2026-04-01 is colored datelinecolor
2026-05-31 is colored datelinecolor

[Start Gültigkeit erp_2026_02 (01.04.2026)] happens on 2026-04-01
[Ende Gültigkeit erp_2026_02 (31.05.2026)] happens on 2026-05-31

[erp_2026_02] starts 2026-04-01
[erp_2026_02] ends 2026-05-31
[erp_2026_02] is colored in erpfdcolor

-- Arzneimittelverordnung --

[kbv.ita.erp 1.1.2] starts 2025-07-15 and ends 2026-03-31
[kbv.ita.erp 1.1.2] is colored in kbvcolor

[kbv.ita.erp 1.3.0] starts 2025-10-01 and ends 2026-05-31
[kbv.ita.erp 1.3.0] is colored in kbvcolor

-- DiGA Verordnung --

[kbv.itv.evdga 1.1.1] starts 2025-07-15 and ends 2026-03-31
[kbv.itv.evdga 1.1.1] is colored in evdgacolor

[kbv.itv.evdga 1.2.0] starts 2025-10-01 and ends 2026-05-31
[kbv.itv.evdga 1.2.0] is colored in evdgacolor

-- Abgabedaten PKV --

[de.abda.erezeptabgabedatenpkv 1.3.0] starts 2025-07-15 and ends 2026-01-11
[de.abda.erezeptabgabedatenpkv 1.3.0] is colored in davcolor

[de.abda.erezeptabgabedatenpkv 1.4.0] starts 2025-10-01 and ends 2026-05-31
[de.abda.erezeptabgabedatenpkv 1.4.0] is colored in davcolor

-- E-Rezept Workflow --

[de.gematik.erezept-workflow.r4 1.4.3] starts 2025-07-15 and ends 2026-01-11
[de.gematik.erezept-workflow.r4 1.4.3] is colored in gematikcolor

[de.gematik.erezept-workflow.r4 1.5.0] starts 2025-10-01 and ends 2026-05-31
[de.gematik.erezept-workflow.r4 1.5.0] is colored in gematikcolor

-- Profile für FdVs --

[de.gematik.erezept-workflow.r4(FDV) 1.4.3] starts 2025-07-15 and ends 2026-03-31
[de.gematik.erezept-workflow.r4(FDV) 1.4.3] is colored in kbvcolor

[de.gematik.erezept-workflow.r4(FDV) 1.5.0] starts 2025-10-01 and ends 2026-05-31
[de.gematik.erezept-workflow.r4(FDV) 1.5.0] is colored in kbvcolor

-- Patientenrechnung --

[de.gematik.erezept-patientenrechnung.r4 1.0.4] starts 2025-07-15 and ends 2026-01-11
[de.gematik.erezept-patientenrechnung.r4 1.0.4] is colored in gematikcolor_patrn

[de.gematik.erezept-patientenrechnung.r4 1.1.0] starts 2025-10-01 and ends 2026-05-31
[de.gematik.erezept-patientenrechnung.r4 1.1.0] is colored in gematikcolor_patrn

-- E-Rezept EU Workflow --

[de.gematik.erezept.eu.r4 1.0.0] starts 2025-10-01 and ends 2026-05-31
[de.gematik.erezept.eu.r4 1.0.0] is colored in gematikcolor_eu

@endgantt