@startgantt
!define kbvcolor #ff8c42
!define evdgacolor #ffb685
!define davpkvcolor #6abf69
!define davcolor #91d891
!define gkvsvcolor #A8111E
!define gematikcolor #4a90e2
!define gematikcolor_fdv #5a6fa5
!define gematikcolor_patrn #88d4d8
!define gematikcolor_eu #b3cde3
!define erpfdcolor #90a4ae

!define datelinecolor #f2b6b6

<style>
document {
   BackGroundColor #f5f5f5
}
ganttDiagram {
   task {
      BackGroundColor GreenYellow
      LineColor Green
      FontColor #333333
      FontSize 18
      FontStyle bold
   }
}
</style>

title Zeitleiste der Versionsübergänge der FHIR-Profile
footer Zuletzt verändert am %date("dd.MM.yyyy")

projectscale monthly zoom 3
Project starts 2026-01-02

-- ERP-FD Konfigurationen --

2026-03-31 is colored datelinecolor

[Ende Gültigkeit erp_2026_01 (31.03.2026)] happens on 2026-03-31

[erp_2026_01] starts 2026-01-12
[erp_2026_01] ends 2026-03-31
[erp_2026_01] is colored in erpfdcolor

2026-04-01 is colored datelinecolor
2026-06-30 is colored datelinecolor

[Start Gültigkeit erp_2026_02 (01.04.2026)] happens on 2026-04-01
[Ende Gültigkeit erp_2026_02 (30.06.2026)] happens on 2026-06-30

[erp_2026_02] starts 2026-04-01
[erp_2026_02] ends 2026-06-30
[erp_2026_02] is colored in erpfdcolor

2026-07-01 is colored datelinecolor
2026-09-30 is colored datelinecolor

[Start Gültigkeit erp_2026_03 (01.07.2026)] happens on 2026-07-01
[Ende Gültigkeit erp_2026_03 (30.09.2026)] happens on 2026-09-30

[erp_2026_03] starts 2026-07-01
[erp_2026_03] ends 2026-09-30
[erp_2026_03] is colored in erpfdcolor

2026-10-01 is colored datelinecolor

[Start Gültigkeit erp_2026_04 (01.10.2026)] happens on 2026-10-01
[Ende Gültigkeit erp_2026_03 (30.09.2026)] happens on 2026-09-30

[erp_2026_04] starts 2026-10-01
[erp_2026_04] ends 2026-11-30
[erp_2026_04] is colored in erpfdcolor

-- Arzneimittelverordnung --

[kbv.ita.erp 1.1.2] starts 2026-01-12 and ends 2026-03-31
[kbv.ita.erp 1.1.2] is colored in kbvcolor

[kbv.ita.erp 1.3.2] starts 2026-01-12 and ends 2026-09-30
[kbv.ita.erp 1.3.2] is colored in kbvcolor

[kbv.ita.erp 1.4.0] starts 2026-04-01 and ends 2026-11-30
[kbv.ita.erp 1.4.0] is colored in kbvcolor

-- DiGA Verordnung --

[kbv.itv.evdga 1.1.1] starts 2026-01-12 and ends 2026-03-31
[kbv.itv.evdga 1.1.1] is colored in evdgacolor

[kbv.itv.evdga 1.2.1] starts 2026-01-12 and ends 2026-11-30
[kbv.itv.evdga 1.2.1] is colored in evdgacolor

-- Abgabedaten PKV --

[de.abda.erezeptabgabedatenpkv 1.4.0] starts 2026-01-12 and ends 2026-11-30
[de.abda.erezeptabgabedatenpkv 1.4.0] is colored in davpkvcolor

-- Abgabedaten --

[de.abda.erezeptabgabedaten 1.5.0] starts 2026-01-12 and ends 2026-11-30
[de.abda.erezeptabgabedaten 1.5.0] is colored in davcolor

-- Abrechnungsdaten --

[de.gkvsv.eRezeptAbrechnungsdaten 1.5.1] starts 2026-01-12 and ends 2026-11-30
[de.gkvsv.eRezeptAbrechnungsdaten 1.5.1] is colored in gkvsvcolor

-- E-Rezept Workflow --

[de.gematik.erezept-workflow.r4 1.5.2] starts 2026-01-12 and ends 2026-06-30
[de.gematik.erezept-workflow.r4 1.5.2] is colored in gematikcolor

[de.gematik.erezept-workflow.r4 1.6.0] starts 2026-04-01 and ends 2026-11-30
[de.gematik.erezept-workflow.r4 1.6.0] is colored in gematikcolor

-- Communication Profile - E-Rezept Workflow --

[erp-communications-workflow 1.4.3] starts 2026-01-12 and ends 2026-03-31
[erp-communications-workflow 1.4.3] is colored in kbvcolor

[erp-communications-workflow 1.5.2] starts 2026-01-12 and ends 2026-09-30
[erp-communications-workflow 1.5.2] is colored in kbvcolor

[erp-communications-workflow 1.6.0] starts 2026-04-01 and ends 2026-11-30
[erp-communications-workflow 1.6.0] is colored in kbvcolor

-- Communication Profile - E-Rezept Patientenrechnung --

[erp-communications-patientenrechnung 1.0.4] starts 2026-01-12 and ends 2026-03-31
[erp-communications-patientenrechnung 1.0.4] is colored in kbvcolor

[erp-communications-patientenrechnung 1.1.0] starts 2026-01-12 and ends 2026-11-30
[erp-communications-patientenrechnung 1.1.0] is colored in kbvcolor

-- Patientenrechnung --

[de.gematik.erezept-patientenrechnung.r4 1.1.0] starts 2026-01-12 and ends 2026-11-30
[de.gematik.erezept-patientenrechnung.r4 1.1.0] is colored in gematikcolor_patrn

-- E-Rezept EU Workflow --

[de.gematik.erezept.eu.r4 1.0.0] starts 2026-01-12 and ends 2026-11-30
[de.gematik.erezept.eu.r4 1.0.0] is colored in gematikcolor_eu

@endgantt