@startuml az_patient

title Alternative Zuweisung eines E-Rezeptes aus Sicht des Patienten
hide footbox

actor "Verordnender" as VLE order 0
actor "Versicherter" as PAT order 0
participant "E-Rezept-FdV" as FDV order 0
participant "APOVZD" as APOVZD order 0
participant "Apotheke\nREST-Endpunkt" as ADL order 0

activate VLE
activate PAT

VLE -> PAT -- : printEPrescription(eRpToken): QR-Code
PAT -> FDV ++: scan(QR-Code): eRpToken
FDV -> FDV++: storeERpToken()
deactivate FDV

FDV -> APOVZD++: getPharmacies(): pharmacies
APOVZD --> FDV--: [pharmacies]

FDV -> FDV: filterPharmacies()
FDV --> PAT: displayPharmacies()
PAT -> FDV: selectPharmacy(Belieferungsoption)
FDV --> PAT: getFreeText()
PAT -> FDV: enterFreeText(): freeText
FDV --> PAT: verifyContactInfo()
PAT -> FDV--: confirmContactInfo()

FDV -> FDV: generateUUID(): UUID
FDV -> FDV: generateMessage(\nUUID,\neRpToken,\nfreeText,\ncontactInfo,\ndeliveryAddress\n): Message
FDV -> FDV: encrypt(Message, C.HCI.ENC): encryptMessage
FDV -> ADL: sendMessage(encryptMessage)
ADL --> FDV: ok()
deactivate FDV
deactivate PAT

@enduml