@startuml egk_abrufen
hide footbox
title E-Rezept abrufen mittels eGK in der Apotheke
actor Vers as "Versicherte" #ee8360
actor LE as "Apotheker:in" #ee8360
participant AVS as "AVS abgebende LEI" #ee8360
participant Konnektor #8da5c4
participant FD as "E-Rezept-Fachdienst" #009a7c

Vers -> LE: eGK übergeben/stecken
LE -> AVS: E-Rezept mittels eGK abrufen
    activate AVS #ee8360
AVS -> Konnektor: ReadVSD (PerformOnlineCheck=true, \rReadOnlineReceipt=true)
    activate Konnektor #8da5c4
Konnektor -> Konnektor: VSD-Onlineprüfung
Konnektor --> AVS: ReadVSDResponse \n(VD, PVD, GVD, PN, VSD_Status)
    deactivate Konnektor
AVS -> AVS: KVNR aus PD extrahieren \n("Versicherten_ID")
AVS -> AVS: PN Base64 URL-safe codieren

group opt 
    ref over AVS, Konnektor, FD
        UC 5.2 AuthN Token durch LEI anfordern
    end ref
end

AVS -> FD:  GET /Task?KVNR=K010124021&PNW=H4sIAAAAAAA...
    activate FD #009a7c
FD -> FD: Rollenprüfung Apotheke
FD -> FD: Prüfung Ratelimit Apotheke
FD -> FD: Prüfung PN Status und Zeitstempel
FD -> FD: Suche Task anhand übergebener KVNR
FD -> FD: Filter Tasks nach Task.status = "ready"
FD --> AVS: 200: Bundle{Task, Task, ...}
    deactivate FD

AVS --> LE: :Liste einlösbarer \rE-Rezepte[TaskIDs + AccessCodes] 
LE --> Vers: :eGK zurückgeben
@enduml