@startuml fhir_version_timeline
<style>
root {
    Margin 0 0 0 30
}

timingDiagram {
  .rudevcolor {
    FontColor #000e52
    Fontsize 16
    FontStyle bold
    Backgroundcolor #FEF5AC
  }
  .rucolor {
    FontColor #000e52
    Fontsize 16
    FontStyle bold
    Backgroundcolor #97D2EC
  }
  .tucolor {
    FontColor #ffffff
    Fontsize 16
    FontStyle bold
    BackgroundColor #5F6F94
  }
  .pucolor {
    FontColor #ffffff
    Fontsize 16
    FontStyle bold
    BackgroundColor #25316D
  }
}
</style>
title Zeitleiste der Zustände vom Fachdienst
footer Erstellt am 09.02.2023

concise "RU-DEV" as RUDEV <<rudevcolor>>
concise "RU" as RU <<rucolor>>
concise "TU" as TU <<tucolor>>
concise "PU" as PU <<pucolor>>


'30 days is scaled to 50 pixels
scale 2592000 as 60 pixels
hide time-axis
'manual time-axis
'use date format "dd.MM.yyyy"

@2023/01/01
RUDEV is "FHIR 2022 + 2023"
RU is "FHIR 2022"
TU is "FHIR 2022"
PU is "FHIR 2022"

@2023/04/01
RUDEV is "FHIR 2023"
RU is "FHIR 2022 + 2023"
TU is "FHIR 2022 + 2023"

@2023/07/01
RU is "FHIR 2023"
PU is "FHIR 2022 + 2023"

@2023/10/01
TU is "FHIR 2023"

@2024/01/01
PU is "FHIR 2023"

@2024/02/01
@enduml