@startuml fhir_version_timeline
<style>
timingDiagram {
  .kbvcolor {
    FontColor #ffffff
    Fontsize 16
    FontStyle bold
    Backgroundcolor #c30059
  }
  .gematikcolor {
    FontColor #000e52
    Fontsize 16
    FontStyle bold
    Backgroundcolor #00ff64
  }
  .davcolor {
    FontColor #ffffff
    Fontsize 16
    FontStyle bold
    BackgroundColor #f00000
  }
  .gkvcolor {
    FontColor #ffffff
    Fontsize 16
    FontStyle bold
    BackgroundColor #b10f21
  }
}
</style>
title Zeitleiste der Versionsübergänge der FHIR-Profile
footer Erstellt am 08.05.2023


concise "de.gkvsv.eRezeptAbrechnungsdaten" as GKV <<gkvcolor>>
concise "kbv.ita.erp" as KBV <<kbvcolor>>
concise "de.gematik.erezept-workflow.r4" as gematik <<gematikcolor>>
concise "de.abda.eRezeptAbgabedaten" as DAV <<davcolor>>
concise "de.abda.eRezeptAbgabedatenPKV" as PKV <<davcolor>>
concise "de.gematik.erezept-patientenrechnung.r4" as gematikpkv <<gematikcolor>>


'30 days is scaled to 50 pixels
scale 2592000 as 50 pixels
hide time-axis

@2023/01/01
GKV is 1.2
KBV is 1.0.2
DAV is 1.2
gematik is 1.1.1

@2023/07/01
note bottom of KBV : 01.07.2023 Übergangsphase\nPVS/ZPVS/KIS\nKBV 1.0.2/1.1.0
note bottom of PKV : 01.07.2023
note top of gematik : 01.07.2023\nÜbergangsphase\nFachdienst\nKBV 1.0.2/1.1.0
note bottom of gematik : 01.07.2023\nÜbergangsphase Fachdienst\nCommunication 1.1.1 / 1.2
note bottom of gematikpkv : 01.07.2023
note bottom of DAV : 01.07.2023
note top of GKV : Durch MVO sind 1.0.2 KBV-Profile bis einschl. Q1 2025 zu erwarten
KBV is "1.0.2/1.1.0"
gematik is 1.2
gematikpkv is 1.0
DAV is 1.3
PKV is 1.2
GKV is 1.3

@2024/01/01
note bottom of KBV : 01.01.2024 Ende Übergangsphase\nPVS/ZPVS/KIS\nKBV 1.1.0
note top of gematik : 01.01.2024\nEnde Übergangsphase\nFachdienst\nKBV 1.1.0
note bottom of gematik : 01.01.2024\nEnde Übergangsphase\nFachdienst\nCommunication 1.2
KBV is 1.1.0

@2024/03/01

legend 
Die Angaben auf den Zeitstreifen repräsentieren die Profilversion, nicht die Package-Version. 
end legend

@enduml