@startuml fhir_version_timeline
<style>
timingDiagram {
  .kbvcolor {
    FontColor #ffffff
    Fontsize 16
    FontStyle bold
    Backgroundcolor #c30059
  }
  .gematikcolor {
    FontColor #000e52
    Fontsize 16
    FontStyle bold
    Backgroundcolor #00ff64
  }
  .davcolor {
    FontColor #ffffff
    Fontsize 16
    FontStyle bold
    BackgroundColor #f00000
  }
  .gkvcolor {
    FontColor #ffffff
    Fontsize 16
    FontStyle bold
    BackgroundColor #b10f21
  }
}
</style>
title Zeitleiste der Versionsübergänge der FHIR-Profile
footer Zuletzt verändert am %date("dd.MM.yyyy")


concise "de.gkvsv.eRezeptAbrechnungsdaten" as GKV <<gkvcolor>>
concise "kbv.ita.erp" as KBV <<kbvcolor>>
concise "S_KBV_DARREICHUNGSFORM" as DF <<kbvcolor>>
concise "S_KBV_DMP" as DMP <<kbvcolor>>
concise "de.abda.eRezeptAbgabedaten" as DAV <<davcolor>>
concise "de.abda.eRezeptAbgabedatenPKV" as PKV <<davcolor>>
concise "de.gematik.erezept-workflow.r4" as gematik <<gematikcolor>>
concise "de.gematik.erezept-patientenrechnung.r4" as gematikpkv <<gematikcolor>>


'30 days is scaled to 50 pixels
scale 2592000 as 50 pixels
hide time-axis

@2024/05/01
GKV is 1.3
KBV is 1.1.0
note bottom of KBV : package 1.1.2
DF is 1.12
DMP is 1.05
DAV is 1.3
gematik is 1.2
gematikpkv is 1.0
PKV is 1.2

@2024/07/01
DF is 1.13
note bottom of DF : 01.07.2024\nNeuer Wert: LYO

@2024/10/01
DMP is 1.06
note bottom of DMP : 01.10.2024\nNeue DMP Kennzeichen
DF is 1.14
note bottom of DF : 01.10.2024\nNeue Werte: IID, LIV

@2024/11/01
GKV is 1.4
note bottom of GKV : 01.11.2024\npackage 1.4.0
DAV is 1.4
note top of DAV: Übergangszeit bis 15.04.2025
note bottom of DAV : 01.11.2024\npackage 1.4.1
gematik is 1.3
note top of gematik: Übergangszeit AVS bis 15.01.25\nÜbergangszeit FdV bis 31.03.25
note bottom of gematik : 01.11.2024\npackage 1.3.1
gematikpkv is 1.0
note bottom of gematikpkv : 01.11.2024\npackage 1.0.3

@2025/01/15
gematik is 1.4
note bottom of gematik : 15.01.2025\npackage 1.4.3\nÜbergangszeit bis 15.04.2025
gematikpkv is 1.0
note bottom of gematikpkv : 15.01.2025\npackage 1.0.4
PKV is 1.3
note bottom of PKV : 15.01.2025\npackage 1.3.0


@2025/07/15
gematik is 1.5
note bottom of gematik : (vorläufig) 15.07.2025\npackage 1.5.0

@2025/08/15

legend
Die Profilversion ist in den Zeitstreifen die Packageversion in den Notizen festgehalten
end legend

@enduml