@startuml

start

if(URL parameter pnw exists \n\n A_23450) then (yes)
  :Extract Prüfziffer;
  if(Prüfziffer exists) then (yes)
    :Verify Prüfziffer;
    if(Prüfziffer HMAC valid \nand pz-kvnr exists\n\nA_23450, A_23456-01) then (yes)
      if(Prüfziffer validy period ok\n\nA_23451-1) then (yes)
        :Return 200 - List of prescription for pz-kvnr\n\nA_23452-02;
      else (no)
        :Error 403;
        end
      endif
    else (no)
      :Error 403;
      end
    endif
  else (no)
    if(Prüfungsnachweis Result = 3\n\nA_25206) then (yes)
      :Update PN3 statistic;
      if(URL parameter kvnr exists\n\nA_25208) then (yes)
        if(AcceptPN3 is active\n\nA_25207) then (yes)
          :Return 202 - List of prescription for url-kvnr\n\nA_25209;
        else (no)
          :Error 454;
          end
        endif
	  else (no)
        :Error 455;
        end
	  endif 
    else (no)
      :Error 403;
      end
    endif
  endif
else (no)
  :Error 403;
  end
endif

stop

@enduml